# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 324e53d0bcd7c101be40e6e1014325cb74e0c889a296d5ed39d1f4ad87eab5aa80a67b04efeb026223206d7bd9cdeac7b25c65390ea6a748513d4d20d5644564

test:
  secret_key_base: 1976b45f02fd29f867450ea71fb5557a2760ac4a94243c9d38bea47548e22209e154c07ac3daeb44cca61d5321934edabef4a37c61f0bd64e836c5fa27564151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
